Merge openshift/installer for 4.1.0-rc.1
metalkube/kni-installer pull request #75
Opened 2019-05-09 14:13 UTC by stbenjam

2019-05-09 14:22 UTC, derekhiggins commented
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/628/

2019-05-10 10:42 UTC, hardys commented
Hmm the CI job failed because the branch doesn't rebase cleanly on master, and also if you try to build the branch without rebasing I see this error:

```
pkg/destroy/baremetal/baremetal.go:24:12: undefined: "github.com/openshift-metalkube/kni-installer/vendor/github.com/libvirt/libvirt-go".NewConnect
```

Which is weird because it's defined at https://github.com/libvirt/libvirt-go/blob/master/connect.go#L321 and that's in the vendor dir...

2019-05-10 10:44 UTC, hardys commented
Actually it builds fine with the BUILD/TAGS defined in `05_build_ocp_installer.sh` so doing some local testing with that..

2019-05-10 11:15 UTC, stbenjam commented
CI always fails on rebasing this way, it can't apply the patch.  The branch needs to be checked out.

Although, this is probably not worth testing at the moment - you won't get very far.  OpenShift moved to using api-int DNS address even for ignition, and we don't have that record.  There's work in progress, https://github.com/openshift-metal3/dev-scripts/pull/462, but that PR is not enough.  @celebdor and @cybertron are still working on a solution.

2019-05-13 16:41 UTC, derekhiggins commented
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/633/

2019-05-15 06:28 UTC, markmc requested changes

2019-05-15 06:28 UTC, markmc commented on data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
> +		--manifest-etcd-server-urls={{.EtcdCluster}} \
This line shouldn't have changed - should still use etcd-server-urls function

2019-05-15 06:32 UTC, markmc commented
Another tiny change that could come with the rebase - https://github.com/markmc/kni-installer/commit/36b9ba614e5f25276deb61184b7fbcf775cf88d8

Fine with that going in post-merge though

2019-05-15 06:33 UTC, markmc commented
Apart from those 2 small issues, I don't see any mechanical issues with the rebase. Nicely done!

2019-05-15 13:08 UTC, stbenjam commented
I incorporated https://github.com/markmc/kni-installer/commit/36b9ba614e5f25276deb61184b7fbcf775cf88d8, and fixed the bootkube issue

2019-05-15 13:11 UTC, derekhiggins commented
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/637/

2019-05-16 17:32 UTC, merged