Add api-int record to bootstrap
metalkube/kni-installer pull request #77
Opened 2019-05-10 20:30 UTC by cybertron

Add the hosts plugin to coredns so that we can create a static entry
for api-int.$CLUSTER_DOMAIN. hosts is used because it doesn't have to
be authoritative for the zone and can allow fallthrough of records
that are not found.

2019-05-10 20:33 UTC, cybertron commented
@celebdor This should get api-int working on the bootstrap node too.

2019-05-13 14:51 UTC, stbenjam approved these changes
Master nodes do get their ignition successfully with this change.

2019-05-13 16:31 UTC, derekhiggins commented
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/632/

2019-05-13 16:37 UTC, stbenjam requested changes
D'oh, sorry - I had my change from this morning still applied - https://github.com/openshift-metal3/dev-scripts/pull/531 :-(

With just this, it's not enough.  Ignition hosts aren't pointing at coredns, they're all hitting 192.168.111.1, which doesn't have the api-int record.

2019-05-13 20:22 UTC, stbenjam commented
I added the temporary record to https://github.com/openshift-metal3/dev-scripts/pull/523.  I suppose we still need this as well, for when after the cluster comes up.

2019-05-15 13:24 UTC, stbenjam approved these changes

2019-05-16 17:30 UTC, merged